package model

type DEVICE_TYPE int

const (
	DEVICE_TYPE_MOTOR DEVICE_TYPE = iota + 3
	DEVICE_TYPE_BREAKER
	DEVICE_TYPE_BREAKER_N
	DEVICE_TYPE_D_SWITCH
	DEVICE_TYPE_DOOR
	DEVICE_TYPE_LOCK
	DEVICE_TYPE_AM6108
	DEVICE_TYPE_BODY
	DEVICE_TYPE_AIR
	DEVICE_TYPE_BREAKER_STB3
	DEVICE_TYPE_IRACC
	DEVICE_TYPE_IRACC_GATEWAY
	DEVICE_TYPE_E_VALVE
	DEVICE_TYPE_SWITCH_433
	DEVICE_TYPE_LIGHT
	DEVICE_TYPE_SOIL_SENSOR
	DEVICE_TYPE_BODY_V4
	DEVICE_TYPE_VOLTAGE_MODULE
	DEVICE_TYPE_METER
	DEVICE_TYPE_LORA_PANEL
	DEVICE_TYPE_RELAY_16
	DEVICE_TYPE_RELAY_CHILD
	DEVICE_TYPE_BREAKER_STB3_125_R
	DEVICE_TYPE_BREAKER_STB3_125_RJ
	DEVICE_TYPE_BREAKER_STB3L_125_R
	DEVICE_TYPE_BREAKER_STB3L_125_RJ
	DEVICE_TYPE_WIFI_PLUG
	DEVICE_TYPE_MOTOR_FR
	DEVICE_TYPE_RAIN
	DEVICE_TYPE_DOOR_LOCK
	DEVICE_TYPE_RELAY_8
	DEVICE_TYPE_LIGHTING_MODULE_4
	DEVICE_TYPE_LIGHTING_MODULE_8
	DEVICE_TYPE_LIGHTING_MODULE_16
	DEVICE_TYPE_MOTOR_CURTAIN
	DEVICE_TYPE_WIFI_SWITCH02
)

type Device485 interface {
	GetDevice485Setting() (uint32, byte, byte, byte)
}

type DeviceRelay interface {
	GetRelayDefaultState() byte
}
